package com.yangaobo.expense.agents;

import java.util.List;

public final class ExpenseMultiAgentPlanner {

    public static final String PLAN_VERSION = "my-expense-agent-multi-agent-v1";

    public ExpenseMultiAgentPlan plan(String caseId, String requestId) {
        return new ExpenseMultiAgentPlan(
                PLAN_VERSION,
                caseId,
                requestId,
                List.of(
                        new AgentStepDefinition(
                                1,
                                AgentRole.RECEIPT_EXTRACTION_AGENT,
                                "票据提取 Agent",
                                "INGESTION",
                                "SEQUENTIAL_CHAIN",
                                "DOCUMENT_PREPARATION",
                                List.of(),
                                "",
                                "将 PDF/图片预处理结果转换为结构化票据字段，输出字段置信度和校验线索。",
                                List.of("documentText", "documentImage", "caseClaimedAmount"),
                                List.of("extractedFields", "confidence", "validationHints"),
                                List.of(),
                                false,
                                AgentFailurePolicy.REQUIRE_HUMAN_REVIEW,
                                1,
                                "审核员人工补录票据字段"),
                        new AgentStepDefinition(
                                2,
                                AgentRole.MCP_CONTEXT_AGENT,
                                "申请人与历史经费上下文 Agent",
                                "EVIDENCE_COLLECTION",
                                "PARALLEL",
                                "EVIDENCE_COLLECTION",
                                List.of(AgentRole.RECEIPT_EXTRACTION_AGENT),
                                "",
                                "通过只读 MCP Tool 查询申请人、项目预算、历史经费报销和重复票据证据。",
                                List.of("ownerSubject", "projectCode", "documentSha256"),
                                List.of("applicantContext", "duplicateCheck", "historyEvidence"),
                                List.of(
                                        "get_applicant_profile",
                                        "get_reimbursement_accounts",
                                        "get_project_budget_balance",
                                        "check_duplicate_document",
                                        "get_fund_reimbursement_history"),
                                false,
                                AgentFailurePolicy.RETRY_THEN_HUMAN_REVIEW,
                                3,
                                "审核员查看缓存证据并标记依赖异常"),
                        new AgentStepDefinition(
                                3,
                                AgentRole.POLICY_RAG_AGENT,
                                "制度检索 Agent",
                                "EVIDENCE_COLLECTION",
                                "PARALLEL",
                                "EVIDENCE_COLLECTION",
                                List.of(AgentRole.RECEIPT_EXTRACTION_AGENT),
                                "",
                                "按经费用途、地区、校园级别和报销日期检索制度片段，并保留可追溯引用。",
                                List.of("category", "region", "campusLevel", "expenseDate"),
                                List.of("policyFindings", "citations"),
                                List.of("calculate_allowed_amount", "validate_invoice_number"),
                                false,
                                AgentFailurePolicy.RETRY_THEN_HUMAN_REVIEW,
                                2,
                                "审核员选择制度版本并补充引用"),
                        new AgentStepDefinition(
                                4,
                                AgentRole.RISK_RULE_AGENT,
                                "风险规则 Agent",
                                "RISK_DECISION",
                                "ROUTER",
                                "RISK_ROUTING",
                                List.of(AgentRole.MCP_CONTEXT_AGENT, AgentRole.POLICY_RAG_AGENT),
                                "按风险等级、依赖失败和资料缺失路由到自动通过、人工复核、升级或补资料。",
                                "调用 Java 确定性风险规则合成风险信号、分值和是否需要人工复核。",
                                List.of("extractedFields", "policyFindings", "duplicateCheck"),
                                List.of("riskScore", "riskLevel", "riskSignals"),
                                List.of(),
                                false,
                                AgentFailurePolicy.STOP_AND_ESCALATE,
                                1,
                                "技术值班确认规则配置"),
                        new AgentStepDefinition(
                                5,
                                AgentRole.REVIEW_SUMMARY_AGENT,
                                "复核摘要 Agent",
                                "HUMAN_REVIEW",
                                "DEBATE_ASSIST",
                                "HIGH_RISK_REVIEW",
                                List.of(AgentRole.RISK_RULE_AGENT),
                                "仅当高风险、制度冲突、金额差异或疑似重复报销时生成正反证据摘要，最终交给人工。",
                                "面向审核员组织制度引用、风险信号、MCP 证据和失败恢复信息。",
                                List.of("policyFindings", "riskSignals", "workflowSteps"),
                                List.of("reviewSummary", "humanDecisionHints"),
                                List.of(),
                                false,
                                AgentFailurePolicy.REQUIRE_HUMAN_REVIEW,
                                1,
                                "审核员直接查看原始证据链"),
                        new AgentStepDefinition(
                                6,
                                AgentRole.APPROVED_SETTLEMENT_AGENT,
                                "审批后入账 Agent",
                                "SETTLEMENT",
                                "SEQUENTIAL_CHAIN",
                                "APPROVED_WRITEBACK",
                                List.of(AgentRole.RISK_RULE_AGENT),
                                "仅当路由结果为 LOW_RISK_AUTO_APPROVE 或人工审批通过后允许执行。",
                                "仅在确定性审批通过后调用写 MCP Tool，依次扣减共享项目预算、登记经费报销、提交入账并回写票据历史。",
                                List.of("approvedDecision", "approvedAmount", "approvalReference"),
                                List.of("budgetDebitId", "reimbursementId", "postingId", "postingStatus", "historyRecordId"),
                                List.of(
                                        "debit_project_budget",
                                        "submit_fund_reimbursement",
                                        "submit_fund_posting",
                                        "record_fund_reimbursement_history",
                                        "save_review_evidence"),
                                true,
                                AgentFailurePolicy.IDEMPOTENT_WRITE_RETRY,
                                3,
                                "财务复核内部入账请求状态并人工补偿")));
    }
}
