package com.yangaobo.expense.common.error;

public enum CampusFundFlowErrorCode {
    VALIDATION_FAILED,
    EXPENSE_CASE_NOT_FOUND,
    INVALID_STATE_TRANSITION,
    OPTIMISTIC_LOCK_CONFLICT,
    DUPLICATE_REQUEST,
    POLICY_NOT_FOUND,
    DOCUMENT_REJECTED,
    DEPENDENCY_UNAVAILABLE,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
